#' Simulate some potential outcomes
#'
#' Makes binary causal state, binary valued potential outcomes.
#' @param n number of individuals
#' @param seed integer value for random seed
#' @return data.table with potential outcomes
#' @import data.table
#' @export
simulate_potential_outcomes <- function(n,
                                        seed = sample.int(.Machine$integer.max, 1))
{
  set.seed(seed)
  outcome_values <- c(1, 0)
  prob_y1 <- .55
  prob_y0 <- .45
  DATA <- data.table(
    y0 = 1 * (runif(n) < prob_y0),
    y1 = 1 * (runif(n) < prob_y1))
  attr(DATA, "seed") <- seed
  DATA
}

#' Simulate a simple experiment
#'
#' Simulates potential outcomes and adds a treatment variable
#' @param n number of individuals
#' @param prob_treatment probability of treatment
#' @param seed integer value for random seed
#' @return data.table with potential outcomes
#' @import data.table
#' @export
simulate_simple_experiment <- function(n, prob_treatment = .5,
                                       seed = sample.int(.Machine$integer.max, 1))
{
  set.seed(seed)
  DATA <- simulate_potential_outcomes(n, seed = seed)
  DATA[, prob := prob_treatment]
  DATA[, d := 1 * (runif(n) < prob)]
  DATA[, y := d * y1 + (1 - d) * y0]
  DATA[, `:=`(y1 = NULL, y0 = NULL)]
  attr(DATA, "seed") <- seed
  DATA
}

#' Calculate naive difference in means
#'
#' Calculate naive difference in means
#' @param DATA data.table generated by simulate_simple_experiment
#' @return estimated average
#' @import data.table
#' @export
calc_naive_difference_in_means <- function(DATA)
{
  DATA[, mean(y[d == 1]) - mean(y[d == 0])]
}

#' Simulate an observational study
#'
#' This study will all individuals to select their treatment value
#' based on their potential outcomes
#' @param n number of individuals
#' @param seed integer value for random seed
#' @return data.table with potential outcomes
#' @import data.table
#' @export
simulate_observational_data <- function(n,
                                        seed = sample.int(.Machine$integer.max, 1))
{
  set.seed(seed)
  DATA <- simulate_potential_outcomes(n, seed = seed)
  DATA[, prob := plogis(-2 + 4 * (y1 - y0))]
  DATA[, d := 1 * (runif(n) < prob)]
  DATA[, y := d * y1 + (1 - d) * y0]
  DATA[, `:=`(y1 = NULL, y0 = NULL, prob = NULL)]
  attr(DATA, "seed") <- seed
  DATA
}
